name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Submodule SQLiteCpp
      run: |
        git submodule init
        git submodule update
    - name: CMake generate & build
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
